### PR TITLE
Ti linux 4.19.y

### PR DESCRIPTION
**Pull request by bob-ed**
I have a BBB and am interested in the linux-kernel-dev/tree/ti-linux-4.19.y
download.
what are your requirements?
First time I've tried to access anything....
robert stahl

### CODE REVIEW

**Comment by RobertCNelson** [comment]
> I have a BBB and am interested in the linux-kernel-dev/tree/ti-linux-4.19.y
> download.
> what are your requirements?
> First time I've tried to access anything....
> robert stahl

```
git clone https://github.com/RobertCNelson/ti-linux-kernel-dev.git
cd ti-linux-kernel-dev/
git checkout origin/ti-linux-4.19.y -b tmp
./build_deb.sh
```

Then just install on your BBB..

Regards,

**Comment by bob-ed** [comment]
Do I run that in the BBB terminal ?  The instructions on line were using a iso image file with windows 10 to a eMMC flash storage.

Thank you

Regards,
rstahl

Stay Safe !

**Comment by RobertCNelson** [comment]
Sure, but it'll take between 10~12 hours on the BeagleBone..

Grab VMWare/VirtualBox install Ubuntu/Debian/Fedora and build the kernel, and then copy the deb file to the BBB..

Regards,

**Comment by bob-ed** [comment]
Just came across your msg....

I think I’ll use the second option ! ;-)

Thank you...

Regards



Stay Safe !

**Pull request closed without merging**
